Aufgabe 1a

In [8]:
import numpy as np
A = np.matrix('1 2 3 4; 2 3 4 1; 3 4 1 2; 4 1 2 3')
B = np.matrix('5 4 3 2; 4 3 2 5; 3 2 5 4; 2 5 4 3')
b = np.matrix('1; 2; 3; 4')

In [16]:
print(np.matmul(A, b))

[[30]
 [24]
 [22]
 [24]]


In [17]:
print(np.matmul(B, b))

[[30]
 [36]
 [38]
 [36]]


In [18]:
print(np.transpose(A))

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]
 [4 1 2 3]]


In [20]:
print(np.transpose(B))

[[5 4 3 2]
 [4 3 2 5]
 [3 2 5 4]
 [2 5 4 3]]


In [21]:
print(np.matmul(np.transpose(A), A))

[[30 24 22 24]
 [24 30 24 22]
 [22 24 30 24]
 [24 22 24 30]]


In [22]:
print(np.matmul(np.transpose(B), B))

[[54 48 46 48]
 [48 54 48 46]
 [46 48 54 48]
 [48 46 48 54]]


Aufgabe 1b

In [25]:
print(np.matmul(A[3,:], B[:, 1]))

[[38]]


Aufgabe 2b

In [26]:
print(A.sum(axis=0))

[[10 10 10 10]]


In [27]:
print(B.sum(axis=1))

[[14]
 [14]
 [14]
 [14]]
